//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public int OrderStatusId { get; set; }
        public string StatusNameRus { get; set; }
        public string StatusNameUkr { get; set; }
    }
}
